# Reply to issue labeling (trusted actors only)
name: Welcome New Contributor

on:
  issues:
    types:
      - labeled

permissions:
  issues: write

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Greet new proposition (trusted labelers only)
        if: >
          github.event.label.name == 'ðŸ“„ Grant application' &&
          (github.event.sender.type != 'Bot') &&
          (github.event.sender.login == 'aquint-zama' || github.event.sender.login == 'zaccherinij')
        uses: peter-evans/create-or-update-comment@ca08ebd5dc95aa0cd97021e9708fcd6b87138c9b
        with:
          token: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello  _**${{ github.event.issue.user.login }}**_,

            Thank you for your Grant application! Our team will review and add comments in your issue! In the meantime:
            1. Join the [FHE.org discord server](https://discord.fhe.org/) for any questions (pick the Zama library channel you will use).
            2. Ask questions privately: [bounty@zama.ai](mailto:bounty@zama.ai).
